# Generated by Django 5.0.4 on 2024-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('calories', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
