# Generated by Django 5.0.4 on 2024-05-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='calories',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
